# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.13.1

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn install
          - npm run lint
          - npm run build
  branches:
    dev-stage:
    - step:
        name: Build
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn install
          - npm run lint
          - npm run build
    - step:
        name: Deploy to stage
        deployment: staging
        script:
          - echo "Deploying to test environment"
          - git push https://heroku:$HEROKU_TOKEN@git.heroku.com/intelico-one-stage.git dev-stage:master
