export const bgImages = [
  {
    id: 1,
    name: 'default',
    url: 'assets/bg_images/bg.jpg'
  }, {
    id: 2,
    name: 'bg2',
    url: 'assets/bg_images/bg2.jpg'
  }, {
    id: 3,
    name: 'bg3',
    url: 'assets/bg_images/bg3.jpg'
  }, {
    id: 4,
    name: 'bg4',
    url: 'assets/bg_images/bg4.jpg'
  }, {
    id: 5,
    name: 'bg5',
    url: 'assets/bg_images/bg5.jpg'
  }, {
    id: 6,
    name: 'bg6',
    url: 'assets/bg_images/bg6.jpg'
  }, {
    id: 7,
    name: 'bg7',
    url: 'assets/bg_images/bg7.jpg'
  }, {
    id: 8,
    name: 'bg8',
    url: 'assets/bg_images/bg8.jpg'
  }, {
    id: 9,
    name: 'bg9',
    url: 'assets/bg_images/bg9.jpg'
  }, {
    id: 10,
    name: 'bg10',
    url: 'assets/bg_images/bg10.jpg'
  }, {
    id: 11,
    name: 'bg11',
    url: 'assets/bg_images/bg11.jpg'
  }, {
    id: 12,
    name: 'bg12',
    url: 'assets/bg_images/bg12.jpg'
  }
];
